baseURL = "https://snowdreams1006.github.io/hugo-plugin-readmore/"
languageCode = "zh-cn"
title = "hugo-plugin-readmore"
theme = "ananke"

[params.plugins.readmore]
blogId = "15702-1569305559839-744"
name = "雪之梦技术驿站"
qrcode = "https://snowdreams1006.github.io/snowdreams1006-wechat-public.jpeg"
keyword = "vip"